#!/bin/bash -e

if test ! -f docker-compose.yml; then
  echo Please run this script from directory wiith docker-compose.yml file.
  exit 1
fi

echo "# This section is generated by ../$0"
echo "# You may need to regenerate it per each 'docker-compose up' command"
echo "# NOTE this is only supported on linux"
echo 'hosts:'
for container in hadoop-master hadoop-slave{1,2,3}; do
  container_id=$(docker-compose ps -q $container)
  container_ip=$(docker exec $container_id ifconfig eth0 | grep 'inet addr' | awk '{print $2 }' | cut -d : -f 2)
  echo "  $container: $container_ip"
done
echo "# End of generated section"
